version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
  working_directory: ~/Software-Engineering/folder
  docker:
    - image: cimg/node:lts
  steps:
    - checkout:
        path: ~/Software-Engineering
    - run: npm install
